### ISSUE TITLE
Can LPRNet read 2 row plates?

### ISSUE THREAD

**Issue by richardgohth** [opencv/openvino_training_extensions#213]
Hi
Can LPRNet be trained to read 2 row or multi-row plates?
Thank you

**Comment by AlexanderDokuchaev** [comment]
Hi @richardgohth 
No, LPRNet used CTC loss that works only with one-line text.
To understand how CTC works you can read [original paper](https://www.cs.toronto.edu/~graves/icml_2006.pdf), [Towards Data Science](https://towardsdatascience.com/build-a-handwritten-text-recognition-system-using-tensorflow-2326a3487cd5) or [Distill](https://distill.pub/2017/ctc/).

**Comment by richardgohth** [comment]
Thank you.
Will appreciate your advise on what to use for 2 row plate. Thank you.

**Comment by AlexanderDokuchaev** [comment]
@grib0ed0v

**Comment by grib0ed0v** [comment]
Hi @richardgohth ! Thanks for the interest to **LPRNet**:)

Without re-training current **LPRNet** snapshot can't recognize 2-line car license plates.
Even if you retrain the model, I would not recommend to use it "as is". 
IMHO, it's better to split the lines and do recognition one-by-one, since this approach is more scalable (can handle _2,3,5,N-lines_ in theory). For example, you can refer to [PixelLink Text Detector](https://github.com/opencv/open_model_zoo/blob/master/models/intel/text-detection-0004/description/text-detection-0004.md) and adopt it for 2-line LPs.

**Comment by richardgohth** [comment]
Thank you very much.
For the existing LPRNet here, what is the maximum no of characters per row?
If limited to Chinese number plate length, how can the max length be increased?
Thank you

**Comment by AlexanderDokuchaev** [comment]
@richardgohth 
Currently set 20, but it's set as `2 x real_max_length' 
https://github.com/opencv/openvino_training_extensions/blob/develop/tensorflow_toolkit/lpr/chinese_lp/config.py#L21

**Comment by richardgohth** [comment]
Thank you
